### ISSUE TITLE
Is it not possible to build a signed (!!!) APK with the current appodeal-cordova Plugin

### ISSUE THREAD

**Issue by RonnySchleicher** [appodeal/appodeal-cordova-plugin#40]
## important NOTE
❗️ The error occurs only when you create a **Signed APK** ❗️ 
If you create a 'normal' APK or a Debug Version is everything okay.

### Systems:
* Windows 10 Pro 64 bit, Core i7, 8GB RAM, all updates installed with Android Studio 2.3.3, Cordova 6.5
* iMac (Retina 5K, 27 Zoll), Core i7, 16GB RAM, macOS Sierra 10.12.6, all updates installed with Android Studio 2.3.3, Cordova 6.5
### Steps to Reproduce
* create a fresh new Android Project, only with the appodeal-cordova-plugin
* use follow script (in this sample for Windows)
```
call cordova create PhoneGap_android de.test.test Test
cd PhoneGap_android
call cordova platform add android
call cordova plugin add https://github.com/appodeal/appodeal-cordova-plugin.git#cordova2
call cordova plugin ls

pause
```
#### First Problem
The first Error is a minSdkVersion conflict
![image](https://user-images.githubusercontent.com/1914203/29123957-b6eda20e-7d17-11e7-8321-69844c15eed6.png)

#### Second Problem
After fix this error, and create a SIGNED APK, the next error occure

![image](https://user-images.githubusercontent.com/1914203/29124082-21947fb0-7d18-11e7-8ecd-1a06ae36b965.png)

#### Thrid Problem
After, i have testet the Google way. See
https://developer.android.com/studio/build/multidex.html
but i became other error messages when i create a SIGNED APK

![image](https://user-images.githubusercontent.com/1914203/29124306-dd87469e-7d18-11e7-9730-7aef621a2913.png)

![image](https://user-images.githubusercontent.com/1914203/29124321-eb57cf82-7d18-11e7-8621-a2d1d464f219.png)

## important NOTE
❗️ The error occurs only when you create a **Signed APK** ❗️ 
If you create a 'normal' APK or a Debug Version is everything okay.

**Comment by RonnySchleicher** [comment]
Nochmal in den Appodeal Chat geschrieben mit Verweis/Link auf das Issue und der Frage, ob das so der richtige Weg ist Fehler dieser Art zu melden.

**Comment by Tamplier** [comment]
Hi, @RonnySchleicher!
**First problem.**
Appodeal plugin really supports API 9. The error occurs because of new version of google play services. You can choose between old google play services library (9.+) with minSDKVersion 9 and new google play services with minSDKVersion 14.
**Second problem**
If you met problem with 64K limitation of methods in dex, you can try our special build:
https://github.com/appodeal/appodeal-cordova-maxdex-plugin.git#cordova2

If it won't help, it's better to get the following build:
https://github.com/appodeal/appodeal-cordova-nodex-plugin.git#cordova2
Only in that case you should enable multidex.

**Third problem**
OutOfMemory error just means that you should allow java to use more memory for building your project (build with multidex enabled really requires more resources). You should open your build.gradle and add the following code to "android" section:
```
dexOptions {
		javaMaxHeapSize "2g"
	}
```
Also it's possible that you might need to create gradle.properties file in your <project_folder>/platforms/android with the following content:
`org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m`

**Comment by RonnySchleicher** [comment]
With the latest Version of
```
https://github.com/appodeal/appodeal-cordova-plugin.git
```
I can build a signed apk. Thanks or the help. I close the Issue.
